apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: sparatan/aks-nodejs-argocd
  newTag: 5bd25d5b1f5199ada74bc716038a4a5c5e9079b2
